Naming fix and added Client controller
IvoDijkman/ApotheekApp pull request #55
Opened 2024-04-10 09:47 UTC by YueYuenu

2024-05-14 09:14 UTC, YueYuenu commented
Also removed unneeded async and set the save changes as async

2024-05-14 10:07 UTC, Thimotheo approved these changes

2024-05-21 11:20 UTC, OliverReifler requested changes
R43 Delete comments

R74 return NotFound(ex.Message);

2024-05-21 11:42 UTC, OliverReifler approved these changes

2024-05-21 11:43 UTC, merged